#!/usr/bin/env python3
"""Generate a self-contained .clangd config for a CMake cross build.

The compile database keeps the real cross compiler as argv[0]. clangd still
parses it with Clang, so this script queries that compiler for its C++ system
include search list and emits a Clang-compatible target and sysroot.
"""
import argparse
import os
import subprocess
import sys


def discover_system_includes(compiler):
    """Return the cross compiler's C++ system include directories.

    GCC prints the list between stable marker lines when invoked with ``-v``.
    The caller must provide any vendor-required environment, such as
    ``STAGING_DIR``, before invoking this script.
    """
    result = subprocess.run(
        [compiler, "-E", "-x", "c++", "-v", "-"],
        input="",
        text=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode:
        raise RuntimeError(
            "cross compiler include query failed (exit {}):\n{}".format(
                result.returncode, result.stderr.strip()))

    begin = "#include <...> search starts here:"
    end = "End of search list."
    collecting = False
    include_dirs = []
    for line in result.stderr.splitlines():
        stripped = line.strip()
        if stripped == begin:
            collecting = True
            continue
        if stripped == end:
            break
        if collecting and stripped:
            path = os.path.realpath(stripped)
            if os.path.isdir(path) and path not in include_dirs:
                include_dirs.append(path)

    if not include_dirs:
        raise RuntimeError(
            "could not find C++ system include paths in compiler output:\n{}".format(
                result.stderr.strip()))
    return include_dirs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", required=True, help="real cross C++ compiler")
    parser.add_argument("--compile-commands-dir", required=True,
                        help="directory holding compile_commands.json")
    parser.add_argument("--output", required=True, help="path to .clangd")
    parser.add_argument("--target-triple", required=True,
                        help="Clang-compatible target triple")
    parser.add_argument("--sysroot", required=True,
                        help="target rootfs passed to Clang as --sysroot")
    parser.add_argument("--remove", action="append", default=None,
                        help="flag glob to remove (repeatable)")
    args = parser.parse_args()

    compiler = os.path.abspath(args.compiler)
    include_dirs = discover_system_includes(compiler)
    removes = args.remove if args.remove else ["-mfloat-abi=*", "-mfpu=*"]
    lines = [
        "# Generated by gen_clangd.py — do not edit.",
        "CompileFlags:",
        "  CompilationDatabase: {}".format(args.compile_commands_dir),
        "  Remove:",
    ]
    lines.extend("    - {}".format(item) for item in removes)
    lines.extend([
        "  Add:",
        "    - --target={}".format(args.target_triple),
        "    - --sysroot={}".format(os.path.abspath(args.sysroot)),
    ])
    lines.extend("    - -isystem{}".format(path) for path in include_dirs)

    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")

    sys.stderr.write(
        "wrote {} with {} cross C++ system include directories\n".format(
            args.output, len(include_dirs)))


if __name__ == "__main__":
    main()
