#!/usr/bin/env python3
"""Generate a .clangd config for cross-compiled code (project-agnostic).

clangd parses with its own clang frontend, so GCC-only flags such as
-mfloat-abi= and -mfpu= must be removed or clangd reports them as unsupported.
Full system-header and builtin-macro fidelity for a cross target additionally
requires launching clangd with --query-driver pointing at the cross compiler;
this script prints that recommendation because --query-driver is a clangd
command-line flag and cannot live inside .clangd.
"""
import argparse
import os
import sys


def derive_query_glob(compiler):
    comp_dir = os.path.dirname(os.path.abspath(compiler))
    base = os.path.basename(compiler)
    # arm-openwrt-linux-muslgnueabi-g++ -> arm-openwrt-linux*g*
    prefix = base.split("-")[0]
    return os.path.join(comp_dir, prefix + "*g*")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", required=True, help="cross C++ compiler")
    parser.add_argument("--compile-commands-dir", required=True,
                        help="directory holding compile_commands.json")
    parser.add_argument("--output", required=True, help="path to .clangd")
    parser.add_argument("--remove", action="append", default=None,
                        help="flag glob to remove (repeatable)")
    parser.add_argument("--add", action="append", default=None, dest="add_flags",
                        metavar="FLAG", help="flag to add (repeatable)")
    args = parser.parse_args()

    removes = args.remove if args.remove else ["-mfloat-abi=*", "-mfpu=*"]
    compiler = os.path.abspath(args.compiler)

    lines = [
        "# Generated by gen_clangd.py — do not edit.",
        "CompileFlags:",
        "  CompilationDatabase: {}".format(args.compile_commands_dir),
        "  Compiler: {}".format(compiler),
    ]
    if removes:
        lines.append("  Remove:")
        lines.extend("    - {}".format(item) for item in removes)
    if args.add_flags:
        lines.append("  Add:")
        lines.extend("    - {}".format(item) for item in args.add_flags)

    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")

    sys.stderr.write(
        "wrote {}\n"
        "For full cross-compile header resolution, launch clangd with:\n"
        "  --query-driver={}\n".format(args.output, derive_query_glob(compiler))
    )


if __name__ == "__main__":
    main()
